version: "3.8"

services:
  app:
    build: .    
    volumes:
      - .:/app # Mapeia a pasta atual do seu PC
    networks:
      - rede-local

  web:
    image: bitnami/nginx:latest
    ports:
      - "80:8080" # Acessa via http://localhost no seu PC
    volumes:
      - .:/app
      - ./docker/nginx.conf:/opt/bitnami/nginx/conf/server_blocks/my_app.conf:ro
    networks:
      - rede-local

networks:
  rede-local:
    driver: bridge
