server {
    listen 8080;
    server_name _;
    root /app/public; # Caminho interno do container Bitnami
    index index.php index.html;

    # Logs (opcional, mapeados para o stdout do docker)
    error_log  /opt/bitnami/nginx/logs/error.log;
    access_log /opt/bitnami/nginx/logs/access.log;

    # Suporte a URLs amigáveis do Laravel
    location / {
        try_files $uri $uri/ /index.php?$query_string;
        gzip_static on;
    }

    # Tratamento de arquivos PHP
    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        # 'laravel-app' é o nome do serviço definido no seu stack-laravel.yml
        fastcgi_pass laravel-app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_read_timeout 300;
    }

    # Bloquear acesso a arquivos sensíveis (.env, .git, etc)
    location ~ /\.(?!well-known).* {
        deny all;
    }

    # Otimização de Assets (CSS, JS, Imagens)
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|otf|eot)$ {
        expires max;
        log_not_found off;
    }
}