server {
    listen 80;
    # Aceita qualquer domínio que chegue por aqui via Traefik
    server_name _; 
    root /var/www/html/public;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass 127.0.0.1:9000; # Se o PHP estiver no mesmo container
        # OU use o nome do serviço se forem containers separados:
        # fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}