name: Deploy Laravel Application

on:
  push:
    branches: [main] # Dispara o deploy ao commitar na branch main

jobs:
  laravel-tests:
    name: 🧪 Step 1 - Testes e Qualidade
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring, xml, bcmath, curl

      - name: Install Dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      #- name: Run Tests
      #  run: php artisan test

  deploy-production:
    name: 🚀 Step 2 - Deploy via SSH
    needs: laravel-tests # Só inicia se os testes passarem
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/twn-backoffice

            echo "--- 📥 Baixando novas atualizações ---"
            git pull origin main

            echo "--- 📦 Instalando dependências (Composer) ---"
            composer install --no-dev --optimize-autoloader --no-interaction

            echo "--- 📦 Instalando dependências (NPM) ---"
            npm install 
            npm run build 

            echo "--- 🗄️ Executando Migrations ---"
            php artisan migrate --force

            echo "--- ⚡ Otimizando Cache ---"
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            echo "--- ✅ Deploy Finalizado com Sucesso! ---"
