name: Deploy BlackCloud Laravel

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Deploy via BlackCloud Manager
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 1. Carregar a chave SSH para o Git não pedir senha
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/github_actions

            # 1. Entrar na pasta do projeto (O nome da pasta deve ser igual ao repo)
            cd /var/www/html/twn-backoffice

            # 2. Atualizar o código fonte
            git pull origin main

            # RODAR COMPOSER USANDO A IMAGEM OFICIAL (Garante a pasta vendor)
            docker run --rm -v $(pwd):/app composer:latest install --ignore-platform-reqs --no-dev --optimize-autoloader

            # AJUSTAR PERMISSÕES PARA O PHP-FPM (ID 33 é o www-data)
            sudo chown -R 33:33 .

            # REINICIAR A STACK
            docker stack deploy -c twn-backoffice.yml twn-backoffice

            # 3. Garantir permissões para os containers da Bitnami (User 1001)
            sudo chown -R 1001:1001 .
            sudo chmod -R 775 storage bootstrap/cache

            # 4. Build de Backend (Composer) usando container temporário
            docker run --rm -v $(pwd):/app php:8.3-fpm \
              composer install --no-dev --optimize-autoloader --no-interaction

            # 5. Build de Frontend (Tailwind/Vite) usando container Node
            docker run --rm -v $(pwd):/app node:20-alpine \
              sh -c "cd /app && npm install && npm run build"

            # 6. Rodar Migrations (Conectando na rede privada para achar o MySQL)
            docker run --rm --network rede-cloud-privada -v $(pwd):/app php:8.3-fpm \
              sh -c "curl -sSL https://github.com -o /usr/local/bin/install-php-extensions && 
              chmod +x /usr/local/bin/install-php-extensions && 
              install-php-extensions pdo_mysql && 
              php /app/artisan migrate --force"


            # 7. Limpar e Gerar Caches do Laravel
            docker run --rm -v $(pwd):/app php:8.3-fpm \
              sh -c "php /app/artisan config:cache && php /app/artisan route:cache && php /app/artisan view:cache"

            # 8. Atualizar os serviços no Docker Swarm (Força o reinício dos containers)
            # Substitua 'twn-backoffice' pelo nome da stack que você deu no deploy
            docker service update --force twn-backoffice_app
            docker service update --force twn-backoffice_web
            docker service update --force twn-backoffice_worker
            #docker service update --force twn-backoffice_scheduler
